apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-cluster
  labels:
    app: azure-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azure-cluster
  template:
    metadata:
      labels:
        app: azure-cluster
    spec:
      containers:
        - name: tweetservice-image
          image: kwettercr.azurecr.io/tweet-service:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: azure-cluster
spec:
  type: LoadBalancer
  ports:
    - port: 8081
  selector:
    app: azure-cluster