name: Trigger auto deployment for kwetter-tweet

env:
  username: ${{secrets.DOCKER_USER}}
  password: ${{secrets.DOCKER_PASSWORD}}
# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - './Dockerfile/**'
    - '.github/workflows/kwetter-tweet-AutoDeployTrigger-534407b3-0266-405f-be7a-277a474e1c1c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build project with maven
        run: mvn clean install

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Test
        run: ls

      - name: Docker build
        run: |
          chmod +x ./scripts/docker-build.sh
          ./scripts/docker-build.sh

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KWETTERTWEET_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n kwetter-tweet -g kwetter-resource-group --server docker.io --username  ${{ secrets.KWETTERTWEET_REGISTRY_USERNAME }} --password ${{ secrets.KWETTERTWEET_REGISTRY_PASSWORD }}
            az containerapp update -n kwetter-tweet -g kwetter-resource-group --image renskloosterman/kwetter-tweet:${{ github.sha }}
